### ISSUE TITLE
There's no validation

### ISSUE THREAD

**Issue by naviace** [davispeixoto/PHP-Batch#1]
"Comes with form validation and AJAX interface."  I think that's a lie.
PS: Sorry, this was misposted here, it was meant for some other project.

**Comment by davispeixoto** [comment]
There is no such "Comes with form validation and AJAX interface" anywhere in the documentation.

And this is a work in progress - this is why there are no releases yet. Not even alpha stage.

Please, check these points before reporting an issue. I'm closing this one as it doesn't makes sense.

**Comment by naviace** [comment]
Sorry, this was misposted here, it was meant for some other project.
